# Generated by librat cli 1.0.0

from injector import inject
from src.domain.model.test_a import test_a
from src.domain.repository.test_a import test_aRepository
from src.infrastructure.repository.alchemy.base import AlchemyRepository
from src.infrastructure.repository.alchemy.engine import AlchemyEngine


class Alchemytest_aRepository(AlchemyRepository[test_a], test_aRepository):
    @inject
    def __init__(self, engine: AlchemyEngine):
        super().__init__(engine)