# Generated by librat cli 1.0.0

from pydantic import ConfigDict
from src.application.schema.test_a.short import test_aShortSchema

class test_aDisplaySchema(test_aShortSchema):
    model_config = ConfigDict(from_attributes=True)