# Generated by librat cli 1.0.0

from pydantic import ConfigDict
from src.application.schema.base import BaseEntitySchema


class test_aShortSchema(BaseEntitySchema):
    model_config = ConfigDict(from_attributes=True)