# Generated by librat cli 1.0.0

from abc import ABC
from src.domain.model.test_a import test_a
from src.domain.repository.base import Repository


class test_aRepository(Repository[test_a], ABC):
    pass